// /home/user/advocatus-frontend/src/App.tsx
// PHOENIX PROTOCOL MODIFICATION 15.0 (ARCHITECTURAL ROUTING FIX):
// 1. CRITICAL FIX: The route for `DocumentViewPage` has been corrected to include the
//    necessary `caseId` context.
// 2. The path was changed from `/documents/:documentId` to the architecturally correct
//    `/case/:caseId/documents/:documentId`.
// 3. This resolves the root cause of the incorrect redirect, as the URL generated by
//    the "View Document" button now has an exact match in the application's router.
//
// DEFINITIVE VERSION 8.6 (FINAL ROUTING FIX)
// ...

import React from 'react';
import { BrowserRouter as Router, Routes, Route, Navigate } from 'react-router-dom';
import { AuthProvider } from './context/AuthContext';
import MainLayout from './pages/MainLayout';
import AuthPage from './pages/AuthPage';
import DashboardPage from './pages/DashboardPage';
import CaseViewPage from './pages/CaseViewPage';
import DraftingPage from './pages/DraftingPage';
import AccountPage from './pages/AccountPage';
import AdminDashboardPage from './pages/AdminDashboardPage';
import DocumentViewPage from './pages/DocumentViewPage';
import CalendarPage from './pages/CalendarPage';

const App: React.FC = () => {
  return (
    <AuthProvider>
      <Router>
        <Routes>
          <Route path="/auth" element={<AuthPage />} />

          <Route element={<MainLayout />}>
            <Route path="/" element={<Navigate to="/dashboard" replace />} />
            <Route path="/dashboard" element={<DashboardPage />} />
            <Route path="/case/:caseId" element={<CaseViewPage />} />
            <Route path="/drafting" element={<DraftingPage />} />
            <Route path="/account" element={<AccountPage />} />
            <Route path="/admin" element={<AdminDashboardPage />} />
            
            {/* --- PHOENIX PROTOCOL FIX: This route now correctly matches the URL for viewing a document --- */}
            <Route path="/case/:caseId/documents/:documentId" element={<DocumentViewPage />} />
            
            <Route path="/calendar" element={<CalendarPage />} />
            
          </Route>

          <Route path="*" element={<Navigate to="/dashboard" replace />} />
        </Routes>
      </Router>
    </AuthProvider>
  );
};

export default App;